### ISSUE TITLE
Documentation: wrong opam repo

### ISSUE THREAD

**Issue by MSoegtropIMC** [arthuraa/deriving#14]
The ReadMe at (https://github.com/arthuraa/deriving) states that the opam file for this development lives in the `extra-dev` repo, but actually it is in the `released` repo.

See (https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-deriving/coq-deriving.0.1.0)

**Comment by arthuraa** [comment]
Thanks for noticing this. It has been fixed.
