### ISSUE TITLE
Support mathcomp 2

### ISSUE THREAD

**Issue by SnarkBoojum** [arthuraa/deriving#24]
There's a [porting guide](https://github.com/math-comp/math-comp/blob/master/etc/porting_to_mathcomp2/porting.pdf).

**Comment by arthuraa** [comment]
@SnarkBoojum Sorry, this link points to the QuickChick repository. Did you mean to reference something else?

**Comment by arthuraa** [comment]
MathComp 2.0.0 is officially supported now.
